# Generated by Django 3.2.19 on 2023-05-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRED_VERIFY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField()),
                ('password', models.IntegerField()),
                ('type_login', models.CharField(choices=[('A', 'Admin'), ('T', 'Teacher'), ('S', 'Student')], max_length=1)),
            ],
        ),
    ]
