# Generated by Django 3.2.19 on 2023-05-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred_verify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cred_verify',
            name='password',
        ),
        migrations.AddField(
            model_name='cred_verify',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='cred_verify',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
