# Generated by Django 3.2.19 on 2023-05-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred_verify', '0002_auto_20230507_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='cred_verify',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
