# Generated by Django 3.2.19 on 2023-05-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cred_verify', '0003_cred_verify_password'),
    ]

    operations = [
    ]
