# Generated by Django 3.2.19 on 2023-05-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_windows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os_windows',
            name='computer_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
