# Generated by Django 3.2.19 on 2023-05-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_windows', '0002_alter_os_windows_computer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='os_windows',
            name='id',
        ),
        migrations.AlterField(
            model_name='os_windows',
            name='computer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
