# Generated by Django 3.2.19 on 2023-05-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_windows', '0003_auto_20230504_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='os_windows',
            name='username',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
