# Generated by Django 3.2.19 on 2023-05-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_windows', '0004_os_windows_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os_windows',
            name='softwares_installed',
            field=models.TextField(),
        ),
    ]
