# Generated by Django 3.2.19 on 2023-05-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os_windows', '0005_alter_os_windows_softwares_installed'),
    ]

    operations = [
    ]
