# Generated by Django 3.2.19 on 2023-05-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OS_UNIX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_id', models.IntegerField()),
                ('computer_name', models.CharField(default='', max_length=100)),
                ('os_version', models.CharField(default='', max_length=100)),
                ('serial_number', models.CharField(default='', max_length=30)),
                ('build_version', models.CharField(default='', max_length=100)),
                ('hardware_uuid', models.CharField(default='', max_length=100)),
                ('provisioning_udid', models.CharField(default='', max_length=100)),
                ('hostname', models.CharField(default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(default='', max_length=100)),
                ('softwares_installed', models.CharField(default='', max_length=10000)),
                ('software_count', models.IntegerField()),
                ('authentic_software_count', models.IntegerField()),
                ('unauthentic_software_count', models.IntegerField()),
            ],
        ),
    ]
