# Generated by Django 3.2.19 on 2023-05-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_unix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='os_unix',
            name='id',
        ),
        migrations.AlterField(
            model_name='os_unix',
            name='computer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
