# Generated by Django 3.2.19 on 2023-05-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_unix', '0002_auto_20230504_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='os_unix',
            name='username',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
