# Generated by Django 3.2.19 on 2023-05-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os_unix', '0004_alter_os_unix_softwares_installed'),
    ]

    operations = [
    ]
